/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../Common/game.h"
/* Header for class edu_sjtu_stap_monday_graphics_GameLibJNIWrapper */

#ifndef _Included_edu_sjtu_stap_monday_graphics_GameLibJNIWrapper
#define _Included_edu_sjtu_stap_monday_graphics_GameLibJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_sjtu_stap_monday_graphics_GameLibJNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sjtu_stap_monday_graphics_GameLibJNIWrapper_on_1surface_1created
    (JNIEnv * env, jclass cls) {
    on_surface_created();
}

/*
 * Class:     edu_sjtu_stap_monday_graphics_GameLibJNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_sjtu_stap_monday_graphics_GameLibJNIWrapper_on_1surface_1changed
    (JNIEnv * env, jclass cls, jint width, jint height) {
    on_surface_changed();
}

/*
 * Class:     edu_sjtu_stap_monday_graphics_GameLibJNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sjtu_stap_monday_graphics_GameLibJNIWrapper_on_1draw_1frame
    (JNIEnv * env, jclass cls) {
    on_draw_frame();
}

/*
 * Class:     edu_sjtu_stap_monday_graphics_GameLibJNIWrapper
 * Method:    draw_two_eye
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_sjtu_stap_monday_graphics_GameLibJNIWrapper_draw_1two_1eye
  (JNIEnv *env, jclass cls, jobject mrender, jint screenHeight, jint screenWidth) {

	jclass mcls = (*env)->GetObjectClass(env, mrender);
	jmethodID jmid = (*env)->GetMethodID(env, mcls, "onNewFrame", "()V");

	/* The first call, draw the upper part */
	drowTwoEye(0, 0, screenHeight, screenWidth);
	(*env)->CallVoidMethod(env, mrender, jmid);

	/* The second call, draw the lowerer part */
	drowTwoEye(0, screenHeight/2, screenHeight, screenWidth);
	(*env)->CallVoidMethod(env, mrender, jmid);

}

#ifdef __cplusplus
}
#endif
#endif
