/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_s3d_S3D */

#ifndef _Included_com_intel_s3d_S3D
#define _Included_com_intel_s3d_S3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_s3d_S3D
 * Method:    RenderS3D
 * Signature: (Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_intel_s3d_S3D_RenderS3D
  (JNIEnv *, jclass, jobject, jstring, jobjectArray);

/*
 * Class:     com_intel_s3d_S3D
 * Method:    D3DXViewMatrixToS3D
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_intel_s3d_S3D_D3DXViewMatrixToS3D
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     com_intel_s3d_S3D
 * Method:    D3DXProjMatrixToS3D
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_intel_s3d_S3D_D3DXProjMatrixToS3D
  (JNIEnv *, jclass, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
